import connectDB from "@/lib/mongoose";
import { PropertyModel, PropertyService } from "@/models/Property";
import {
	Property,
	PropertyCondition,
	PropertyStatus,
	PropertyType,
	PropertyVisibility,
} from "@/types/property";
import { NextResponse } from "next/server";

/* ─── reusable owner definitions ──────────────────────────────── */

const owners = {
	adebayo: {
		id: "1",
		name: "Adebayo Johnson",
		username: "adebayoj",
		displayName: "Adebayo J.",
		avatar:
			"https://api.dicebear.com/9.x/initials/svg?seed=AJ&backgroundColor=1e3a5f",
		banner: "/mock-profiles/banner-adebayo.svg",
		email: "adebayo@email.com",
		type: "individual" as const,
		joinDate: "2019-07-22",
		salesCount: 3,
	},
	fatima: {
		id: "2",
		name: "Fatima Ibrahim",
		username: "fatima_i",
		displayName: "Fatima I.",
		avatar:
			"https://api.dicebear.com/9.x/initials/svg?seed=FI&backgroundColor=4a1942",
		banner: "/mock-profiles/banner-fatima.svg",
		email: "fatima@email.com",
		type: "individual" as const,
		joinDate: "2022-02-14",
		salesCount: 1,
	},
	chinedu: {
		id: "3",
		name: "Chinedu Okafor",
		username: "chinedu_o",
		displayName: "Chinedu O.",
		avatar:
			"https://api.dicebear.com/9.x/initials/svg?seed=CO&backgroundColor=0d7377",
		banner: "/mock-profiles/banner-chinedu.svg",
		email: "chinedu@email.com",
		type: "individual" as const,
		joinDate: "2020-04-10",
		salesCount: 5,
	},
	emmanuel: {
		id: "4",
		name: "Emmanuel Uzor",
		username: "manny_uzor",
		displayName: "Emmanuel U.",
		avatar:
			"https://api.dicebear.com/9.x/initials/svg?seed=EU&backgroundColor=5c3d2e",
		banner: "/mock-profiles/banner-emmanuel.svg",
		email: "emmanuel@email.com",
		type: "individual" as const,
		joinDate: "2018-01-20",
		salesCount: 2,
	},
	ngozi: {
		id: "5",
		name: "Ngozi Adekunle",
		username: "ngozi_a",
		displayName: "Ngozi A.",
		avatar:
			"https://api.dicebear.com/9.x/initials/svg?seed=NA&backgroundColor=8b5e3c",
		banner: "/mock-profiles/banner-ngozi.svg",
		email: "ngozi@email.com",
		type: "individual" as const,
		joinDate: "2020-11-05",
		salesCount: 4,
	},
	tunde: {
		id: "6",
		name: "Tunde Bakare",
		username: "tunde_b",
		displayName: "Tunde B.",
		avatar:
			"https://api.dicebear.com/9.x/initials/svg?seed=TB&backgroundColor=2d6a4f",
		banner: "/mock-profiles/banner-tunde.svg",
		email: "tunde@email.com",
		type: "individual" as const,
		joinDate: "2022-03-15",
		salesCount: 0,
	},
	amaka: {
		id: "7",
		name: "Amaka Nwosu",
		username: "amaka_nwosu",
		displayName: "Amaka N.",
		avatar:
			"https://api.dicebear.com/9.x/initials/svg?seed=AN&backgroundColor=6b2fa0",
		banner: "/mock-profiles/banner-amaka.svg",
		email: "amaka@email.com",
		type: "individual" as const,
		joinDate: "2019-12-01",
		salesCount: 2,
	},
	saheed: {
		id: "8",
		name: "Saheed Bello",
		username: "saheed_b",
		displayName: "Saheed B.",
		avatar:
			"https://api.dicebear.com/9.x/initials/svg?seed=SB&backgroundColor=b5651d",
		banner: "/mock-profiles/banner-saheed.svg",
		email: "saheed@email.com",
		type: "individual" as const,
		joinDate: "2021-02-28",
		salesCount: 1,
	},
	primelands: {
		id: "9",
		name: "Primelands Development Ltd",
		username: "primelands_dev",
		displayName: "Primelands Dev.",
		avatar:
			"https://api.dicebear.com/9.x/initials/svg?seed=PD&backgroundColor=1a1a2e",
		banner: "/mock-profiles/banner-primelands.svg",
		email: "info@primelands.ng",
		type: "company" as const,
		joinDate: "2020-06-15",
		salesCount: 12,
	},
	me: {
		id: "owner-1",
		name: "Property Owner",
		username: "plotfolio_user",
		displayName: "Property Owner",
		avatar:
			"https://api.dicebear.com/9.x/initials/svg?seed=PO&backgroundColor=1e3a5f",
		banner: "/mock-profiles/banner-me.svg",
		email: "owner@example.com",
		type: "individual" as const,
		joinDate: "2023-01-15",
		salesCount: 0,
	},
};

/* ─── sample properties data ──────────────────────────────────── */

const sampleProperties: Property[] = [
	// ── My properties (owner-1) ─────────────────────────────────
	{
		id: "1",
		name: "Plot A47 - Maitama District",
		address: "Plot A47, Maitama District, Abuja FCT",
		coordinates: { lat: 9.0765, lng: 7.4951 },
		area: 800,
		propertyType: PropertyType.RESIDENTIAL,
		purchaseDate: new Date("2023-01-15"),
		purchasePrice: 45000000,
		currentValue: 52000000,
		documents: [],
		images: ["/mock-properties/maitama-overview.svg"],
		status: PropertyStatus.OWNED,
		description:
			"Prime residential plot in upscale Maitama district with Certificate of Occupancy.",
		state: "Abuja FCT",
		city: "Maitama",
		country: "Nigeria",
		owner: owners.me,
	},
	{
		id: "7",
		name: "My Property",
		address: "8°55'54.1\"N 7°19'27.7\"E",
		coordinates: { lat: 8.9317, lng: 7.3244 },
		area: 500,
		propertyType: PropertyType.RESIDENTIAL,
		purchaseDate: new Date("2025-11-02"),
		purchasePrice: 0,
		currentValue: 0,
		documents: [],
		images: ["/mock-properties/my-property.svg"],
		status: PropertyStatus.OWNED,
		description: "My personal property",
		country: "Nigeria",
		owner: owners.me,
	},

	// ── Adebayo's properties ────────────────────────────────────
	{
		id: "3",
		name: "Plot B15 - Jahi District",
		address: "Plot B15, Jahi District, Abuja FCT",
		coordinates: { lat: 9.1234, lng: 7.4321 },
		area: 1000,
		propertyType: PropertyType.RESIDENTIAL,
		purchaseDate: new Date("2021-03-10"),
		purchasePrice: 35000000,
		currentValue: 42000000,
		conditions: [PropertyCondition.FENCED, PropertyCondition.CLEARED],
		documents: [],
		images: ["/mock-properties/jahi-garden.svg"],
		status: PropertyStatus.OWNED,
		visibility: PropertyVisibility.PUBLIC,
		description:
			"Large residential plot in developing Jahi district with good road access.",
		state: "Abuja FCT",
		city: "Jahi",
		country: "Nigeria",
		owner: owners.adebayo,
	},
	{
		id: "8",
		name: "Commercial Block - Central Area",
		address: "Plot 12, Central Business District, Abuja FCT",
		coordinates: { lat: 9.0579, lng: 7.4891 },
		area: 2400,
		propertyType: PropertyType.COMMERCIAL,
		purchaseDate: new Date("2019-07-22"),
		purchasePrice: 120000000,
		currentValue: 165000000,
		conditions: [PropertyCondition.PAVED, PropertyCondition.HAS_STRUCTURE],
		documents: [],
		images: ["/mock-properties/commercial-cbd.svg"],
		status: PropertyStatus.FOR_SALE,
		description:
			"High-value commercial block in the Central Business District with existing office structure. Dual access road, serviced with municipal water and power. Ideal for corporate HQ or mixed-use development.",
		state: "Abuja FCT",
		city: "Central Area",
		country: "Nigeria",
		owner: owners.adebayo,
	},

	// ── Fatima's properties ─────────────────────────────────────
	{
		id: "2",
		name: "Plot C23 - Gwarinpa Estate",
		address: "Plot C23, Gwarinpa Estate, Abuja FCT",
		coordinates: { lat: 9.1092, lng: 7.4165 },
		area: 600,
		propertyType: PropertyType.RESIDENTIAL,
		purchaseDate: new Date("2022-08-20"),
		purchasePrice: 18000000,
		currentValue: 22000000,
		conditions: [PropertyCondition.FOUNDATION],
		documents: [],
		images: ["/mock-properties/gwarinpa-foundation.svg"],
		status: PropertyStatus.DEVELOPMENT,
		description:
			"Residential plot in family-friendly Gwarinpa Estate, foundation already laid.",
		state: "Abuja FCT",
		city: "Gwarinpa",
		country: "Nigeria",
		owner: owners.fatima,
	},
	{
		id: "5",
		name: "Plot E09 - Wuye District",
		address: "Plot E09, Wuye District, Abuja FCT",
		coordinates: { lat: 9.0982, lng: 7.4763 },
		area: 750,
		propertyType: PropertyType.RESIDENTIAL,
		purchaseDate: new Date("2022-11-03"),
		purchasePrice: 28000000,
		currentValue: 33000000,
		conditions: [PropertyCondition.CLEARED],
		documents: [],
		images: ["/mock-properties/wuye-corner-plot.svg"],
		status: PropertyStatus.UNDER_CONTRACT,
		description:
			"Well-located plot in Wuye district close to shopping centers.",
		state: "Abuja FCT",
		city: "Wuye",
		country: "Nigeria",
		owner: owners.fatima,
	},
	{
		id: "9",
		name: "Duplex Plot - Life Camp",
		address: "Plot 44, Life Camp, Abuja FCT",
		coordinates: { lat: 9.0823, lng: 7.4032 },
		area: 850,
		propertyType: PropertyType.RESIDENTIAL,
		purchaseDate: new Date("2023-02-14"),
		purchasePrice: 32000000,
		currentValue: 38000000,
		conditions: [PropertyCondition.FENCED, PropertyCondition.CLEARED],
		documents: [],
		images: ["/mock-properties/life-camp-duplex.svg"],
		status: PropertyStatus.FOR_SALE,
		description:
			"Corner plot in Life Camp ideal for a duplex build. Fully fenced with C of O. Close to Shoprite and major road arteries. Owner relocating — priced to sell quickly.",
		state: "Abuja FCT",
		city: "Life Camp",
		country: "Nigeria",
		owner: owners.fatima,
	},

	// ── Chinedu's properties ────────────────────────────────────
	{
		id: "4",
		name: "Plot D31 - Kubwa District",
		address: "Plot D31, Kubwa District, Abuja FCT",
		coordinates: { lat: 9.0839, lng: 7.3492 },
		area: 500,
		propertyType: PropertyType.RESIDENTIAL,
		purchaseDate: new Date("2023-06-15"),
		purchasePrice: 12000000,
		currentValue: 15000000,
		conditions: [PropertyCondition.BUSH],
		documents: [],
		images: ["/mock-properties/kubwa-plot.svg"],
		status: PropertyStatus.FOR_SALE,
		description:
			"Affordable residential plot in Kubwa with survey plan and deed.",
		state: "Abuja FCT",
		city: "Kubwa",
		country: "Nigeria",
		owner: owners.chinedu,
	},
	{
		id: "10",
		name: "Industrial Lot - Idu Layout",
		address: "Plot 7B, Idu Industrial Layout, Abuja FCT",
		coordinates: { lat: 9.0112, lng: 7.3876 },
		area: 3000,
		propertyType: PropertyType.INDUSTRIAL,
		purchaseDate: new Date("2020-04-10"),
		purchasePrice: 55000000,
		currentValue: 72000000,
		conditions: [PropertyCondition.PAVED, PropertyCondition.FENCED],
		documents: [],
		images: ["/mock-properties/idu-industrial.svg"],
		status: PropertyStatus.FOR_SALE,
		description:
			"Expansive industrial lot in Idu Layout. Paved access, perimeter fenced, utility connections available. Suitable for warehousing, manufacturing, or logistics hub. Clear title documentation.",
		state: "Abuja FCT",
		city: "Idu",
		country: "Nigeria",
		owner: owners.chinedu,
	},

	// ── Emmanuel's properties ───────────────────────────────────
	{
		id: "6",
		name: "Plot F22 - Karsana North",
		address: "Plot F22, Karsana North, Abuja FCT",
		coordinates: { lat: 9.0234, lng: 7.4123 },
		area: 900,
		propertyType: PropertyType.RESIDENTIAL,
		purchaseDate: new Date("2021-09-18"),
		purchasePrice: 16000000,
		currentValue: 21000000,
		conditions: [PropertyCondition.CLEARED],
		documents: [],
		images: ["/mock-properties/karsana-expanse.svg"],
		status: PropertyStatus.OWNED,
		visibility: PropertyVisibility.PUBLIC,
		description:
			"Spacious plot in fast-developing Karsana North with good infrastructure.",
		state: "Abuja FCT",
		city: "Karsana",
		country: "Nigeria",
		owner: owners.emmanuel,
	},
	{
		id: "11",
		name: "Farmland - Gwagwalada",
		address: "KM 12, Gwagwalada Road, Abuja FCT",
		coordinates: { lat: 8.9468, lng: 7.0903 },
		area: 5000,
		propertyType: PropertyType.AGRICULTURAL,
		purchaseDate: new Date("2018-01-20"),
		purchasePrice: 8000000,
		currentValue: 14000000,
		conditions: [PropertyCondition.BUSH],
		documents: [],
		images: ["/mock-properties/gwagwalada-farm.svg"],
		status: PropertyStatus.OWNED,
		description:
			"Fertile farmland along the Gwagwalada corridor. Currently uncultivated but road-accessible. Ideal for poultry, crop farming, or agri-business.",
		state: "Abuja FCT",
		city: "Gwagwalada",
		country: "Nigeria",
		owner: owners.emmanuel,
	},

	// ── Ngozi's properties ──────────────────────────────────────
	{
		id: "12",
		name: "Luxury Terrace Plot - Asokoro",
		address: "Plot 18, Asokoro Extension, Abuja FCT",
		coordinates: { lat: 9.0377, lng: 7.5215 },
		area: 1200,
		propertyType: PropertyType.RESIDENTIAL,
		purchaseDate: new Date("2020-11-05"),
		purchasePrice: 85000000,
		currentValue: 110000000,
		conditions: [
			PropertyCondition.FENCED,
			PropertyCondition.PAVED,
			PropertyCondition.HAS_STRUCTURE,
		],
		documents: [],
		images: ["/mock-properties/asokoro-terrace.svg"],
		status: PropertyStatus.FOR_SALE,
		description:
			"Premium plot in Asokoro Extension with partially completed terrace structure. Tarred road, 24-hr security estate, underground drainage. Ideal for luxury residences.",
		state: "Abuja FCT",
		city: "Asokoro",
		country: "Nigeria",
		owner: owners.ngozi,
	},
	{
		id: "13",
		name: "Duplex Land - Guzape District",
		address: "Plot 5, Guzape District, Abuja FCT",
		coordinates: { lat: 9.0298, lng: 7.5108 },
		area: 950,
		propertyType: PropertyType.RESIDENTIAL,
		purchaseDate: new Date("2022-06-30"),
		purchasePrice: 62000000,
		currentValue: 75000000,
		conditions: [PropertyCondition.CLEARED, PropertyCondition.FENCED],
		documents: [],
		images: ["/mock-properties/guzape-duplex.svg"],
		status: PropertyStatus.OWNED,
		visibility: PropertyVisibility.PUBLIC,
		description:
			"Well-positioned plot in Guzape, one of Abuja's most sought-after districts. Cleared and ready for development. Approved building plan available.",
		state: "Abuja FCT",
		city: "Guzape",
		country: "Nigeria",
		owner: owners.ngozi,
	},
	{
		id: "14",
		name: "Mixed-Use Corner - Garki II",
		address: "Plot 33A, Area 11, Garki II, Abuja FCT",
		coordinates: { lat: 9.0452, lng: 7.4878 },
		area: 680,
		propertyType: PropertyType.MIXED_USE,
		purchaseDate: new Date("2021-08-12"),
		purchasePrice: 48000000,
		currentValue: 58000000,
		conditions: [PropertyCondition.PAVED],
		documents: [],
		images: ["/mock-properties/garki-mixed.svg"],
		status: PropertyStatus.FOR_SALE,
		description:
			"Corner plot on a major junction in Garki II. Zoned for mixed-use — retail ground floor with residential upper floors. High foot traffic area with steady rental demand.",
		state: "Abuja FCT",
		city: "Garki",
		country: "Nigeria",
		owner: owners.ngozi,
	},

	// ── Tunde's properties ──────────────────────────────────────
	{
		id: "15",
		name: "Estate Plot - Lokogoma",
		address: "Plot 27, Lokogoma District, Abuja FCT",
		coordinates: { lat: 8.9781, lng: 7.4512 },
		area: 600,
		propertyType: PropertyType.RESIDENTIAL,
		purchaseDate: new Date("2024-01-20"),
		purchasePrice: 20000000,
		currentValue: 24000000,
		conditions: [PropertyCondition.CLEARED],
		documents: [],
		images: ["/mock-properties/lokogoma-estate.svg"],
		status: PropertyStatus.DEVELOPMENT,
		description:
			"Residential plot in the well-planned Lokogoma district. Estate roads, drainage, and streetlights already installed. Foundation expected Q2 2026.",
		state: "Abuja FCT",
		city: "Lokogoma",
		country: "Nigeria",
		owner: owners.tunde,
	},
	{
		id: "16",
		name: "Vacant Land - Lugbe",
		address: "RD-4, FHA Lugbe, Abuja FCT",
		coordinates: { lat: 8.9936, lng: 7.3745 },
		area: 450,
		propertyType: PropertyType.VACANT_LAND,
		purchaseDate: new Date("2023-09-02"),
		purchasePrice: 7500000,
		currentValue: 9500000,
		conditions: [PropertyCondition.BUSH],
		documents: [],
		images: ["/mock-properties/lugbe-vacant.svg"],
		status: PropertyStatus.FOR_SALE,
		description:
			"Affordable vacant land in FHA Lugbe. Uncleared but accessible from Airport Road. Survey plan and allocation papers in order. Great entry-level investment.",
		state: "Abuja FCT",
		city: "Lugbe",
		country: "Nigeria",
		owner: owners.tunde,
	},
	{
		id: "17",
		name: "Shop Plot - Nyanya",
		address: "Block 9, Nyanya Market Extension, Abuja FCT",
		coordinates: { lat: 9.0126, lng: 7.5482 },
		area: 200,
		propertyType: PropertyType.COMMERCIAL,
		purchaseDate: new Date("2022-03-15"),
		purchasePrice: 14000000,
		currentValue: 18000000,
		conditions: [PropertyCondition.HAS_STRUCTURE],
		documents: [],
		images: ["/mock-properties/nyanya-shop.svg"],
		status: PropertyStatus.RENTED,
		visibility: PropertyVisibility.PUBLIC,
		description:
			"Commercial shop space in Nyanya market extension. Currently rented to a building materials trader. Solid rental income with long-term tenant.",
		state: "Abuja FCT",
		city: "Nyanya",
		country: "Nigeria",
		owner: owners.tunde,
	},

	// ── Amaka's properties ──────────────────────────────────────
	{
		id: "18",
		name: "Hilltop Plot - Katampe Extension",
		address: "Plot 8, Katampe Extension, Abuja FCT",
		coordinates: { lat: 9.0892, lng: 7.4587 },
		area: 1500,
		propertyType: PropertyType.RESIDENTIAL,
		purchaseDate: new Date("2019-12-01"),
		purchasePrice: 70000000,
		currentValue: 95000000,
		conditions: [PropertyCondition.ROCKY, PropertyCondition.FENCED],
		documents: [],
		images: ["/mock-properties/katampe-hilltop.svg"],
		status: PropertyStatus.FOR_SALE,
		description:
			"Elevated hilltop plot in Katampe Extension with panoramic views of the city. Rocky terrain — ideal for a luxury villa with a basement. R of O and survey certified.",
		state: "Abuja FCT",
		city: "Katampe",
		country: "Nigeria",
		owner: owners.amaka,
	},
	{
		id: "19",
		name: "Serviced Plot - Mbora District",
		address: "Plot 14, Mbora (Trademoore) Estate, Abuja FCT",
		coordinates: { lat: 9.0045, lng: 7.4234 },
		area: 500,
		propertyType: PropertyType.RESIDENTIAL,
		purchaseDate: new Date("2024-05-18"),
		purchasePrice: 25000000,
		currentValue: 28000000,
		conditions: [PropertyCondition.CLEARED, PropertyCondition.PAVED],
		documents: [],
		images: ["/mock-properties/mbora-serviced.svg"],
		status: PropertyStatus.FOR_SALE,
		description:
			"Serviced plot in Mbora (Trademoore) Estate with tarred roads and estate security. Cleared and ready for immediate construction. All documentation verified.",
		state: "Abuja FCT",
		city: "Mbora",
		country: "Nigeria",
		owner: owners.amaka,
	},

	// ── Saheed's properties ─────────────────────────────────────
	{
		id: "20",
		name: "Bungalow Plot - Dei-Dei",
		address: "Plot 55, Dei-Dei Layout, Abuja FCT",
		coordinates: { lat: 9.1187, lng: 7.3298 },
		area: 400,
		propertyType: PropertyType.RESIDENTIAL,
		purchaseDate: new Date("2024-08-10"),
		purchasePrice: 6000000,
		currentValue: 7800000,
		conditions: [PropertyCondition.BUSH],
		documents: [],
		images: ["/mock-properties/dei-dei-bungalow.svg"],
		status: PropertyStatus.FOR_SALE,
		description:
			"Compact plot in Dei-Dei suitable for a 3-bedroom bungalow. Affordable area with strong growth potential as infrastructure improves. Deed of assignment available.",
		state: "Abuja FCT",
		city: "Dei-Dei",
		country: "Nigeria",
		owner: owners.saheed,
	},
	{
		id: "21",
		name: "Warehouse Land - Zuba",
		address: "KM 5, Zuba Industrial Area, Abuja FCT",
		coordinates: { lat: 9.0734, lng: 7.2156 },
		area: 4000,
		propertyType: PropertyType.INDUSTRIAL,
		purchaseDate: new Date("2021-02-28"),
		purchasePrice: 35000000,
		currentValue: 48000000,
		conditions: [PropertyCondition.CLEARED, PropertyCondition.FENCED],
		documents: [],
		images: ["/mock-properties/zuba-warehouse.svg"],
		status: PropertyStatus.OWNED,
		visibility: PropertyVisibility.PUBLIC,
		description:
			"Large industrial plot in Zuba, major gateway to Abuja from the north-west. Cleared and fenced, ready for warehouse or distribution centre construction.",
		state: "Abuja FCT",
		city: "Zuba",
		country: "Nigeria",
		owner: owners.saheed,
	},

	// ── Primelands Dev (company) properties ─────────────────────
	{
		id: "22",
		name: "Residential Estate Phase 1 - Karshi",
		address: "Estate Road, Karshi New Town, Abuja FCT",
		coordinates: { lat: 8.9612, lng: 7.5731 },
		area: 650,
		propertyType: PropertyType.RESIDENTIAL,
		purchaseDate: new Date("2023-11-01"),
		purchasePrice: 10000000,
		currentValue: 13500000,
		conditions: [PropertyCondition.CLEARED, PropertyCondition.PAVED],
		documents: [],
		images: ["/mock-properties/karshi-estate.svg"],
		status: PropertyStatus.FOR_SALE,
		description:
			"Developer plots in Karshi New Town Phase 1 estate. Roads and drainage complete. Title: Governor's Consent. 24-month installment plan available from Primelands Development.",
		state: "Abuja FCT",
		city: "Karshi",
		country: "Nigeria",
		owner: owners.primelands,
	},
	{
		id: "23",
		name: "Commercial Strip - Apo District",
		address: "Plot 2-4, Apo Mechanic Village Road, Abuja FCT",
		coordinates: { lat: 9.0025, lng: 7.4998 },
		area: 1800,
		propertyType: PropertyType.COMMERCIAL,
		purchaseDate: new Date("2020-06-15"),
		purchasePrice: 90000000,
		currentValue: 125000000,
		conditions: [
			PropertyCondition.PAVED,
			PropertyCondition.HAS_STRUCTURE,
			PropertyCondition.FENCED,
		],
		documents: [],
		images: ["/mock-properties/apo-commercial.svg"],
		status: PropertyStatus.FOR_SALE,
		description:
			"Prime commercial strip facing Apo main road. Three contiguous plots with existing retail structures. High visibility, heavy traffic. Suitable for plaza development or franchise outlets.",
		state: "Abuja FCT",
		city: "Apo",
		country: "Nigeria",
		owner: owners.primelands,
	},
	{
		id: "24",
		name: "Gated Estate Land - Kuje",
		address: "Primelands Gardens, Kuje Area Council, Abuja FCT",
		coordinates: { lat: 8.8794, lng: 7.2287 },
		area: 500,
		propertyType: PropertyType.RESIDENTIAL,
		purchaseDate: new Date("2024-03-01"),
		purchasePrice: 5500000,
		currentValue: 7000000,
		conditions: [PropertyCondition.CLEARED],
		documents: [],
		images: ["/mock-properties/kuje-gated.svg"],
		status: PropertyStatus.FOR_SALE,
		description:
			"Affordable gated-community plot in Kuje. Estate perimeter wall, security gate, and internal roads provided by developer. Flexible payment plan. Perfect starter investment.",
		state: "Abuja FCT",
		city: "Kuje",
		country: "Nigeria",
		owner: owners.primelands,
	},
];

export async function POST() {
	try {
		await connectDB();

		// Clear existing data
		await PropertyModel.deleteMany({});

		// Insert sample data
		const created = await Promise.all(
			sampleProperties.map((property) =>
				PropertyService.createProperty(property),
			),
		);

		return NextResponse.json({
			message: `Successfully seeded ${created.length} properties`,
			properties: created,
		});
	} catch (error) {
		console.error("Error seeding database:", error);
		return NextResponse.json(
			{ error: "Failed to seed database" },
			{ status: 500 },
		);
	}
}
